# 基础镜像
FROM redis
# author
MAINTAINER wolfcode

# 挂载目录
VOLUME /home/trip/redis
# 创建目录
RUN mkdir -p /home/trip/redis
# 指定路径
WORKDIR /home/trip/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/trip/redis/redis.conf
