# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER wolfcode

# 挂载目录
VOLUME /home/trip
# 创建目录
RUN mkdir -p /home/trip
# 指定路径
WORKDIR /home/trip
# 复制jar文件到路径
COPY ./jar/trip-user.jar /home/trip/trip-user.jar
# 启动用户服务
ENTRYPOINT ["java","-jar","trip-user.jar"]
